import { qs, setText, copyText, flashCopied } from "../../js/toolkit.js";

const input = qs("#input");
const out = qs("#output");
const status = qs("#status");
const runBtn = qs("#run");
const copyBtn = qs("#copy");
const clearBtn = qs("#clear");

const MAX_INPUT_CHARS = 120000;
const MAX_OUTPUT_CHARS = 200000;

function show(msg, isError = false) {
  status.style.display = msg ? "" : "none";
  status.style.borderColor = isError ? "rgba(255,120,120,.35)" : "rgba(106,166,255,.25)";
  status.style.background = isError ? "rgba(255,120,120,.10)" : "rgba(106,166,255,.08)";
  setText(status, msg);
}

function tokenizeCurl(cmd) {
  // Very small tokenizer: supports quotes and backslash escapes.
  const s = String(cmd ?? "").trim();
  const tokens = [];
  let cur = "";
  let q = null; // " or '
  for (let i = 0; i < s.length; i++) {
    const ch = s[i];
    if (ch === "\\" && i + 1 < s.length) {
      cur += s[i + 1];
      i++;
      continue;
    }
    if (q) {
      if (ch === q) q = null;
      else cur += ch;
      continue;
    }
    if (ch === "'" || ch === "\"") {
      q = ch;
      continue;
    }
    if (/\s/.test(ch)) {
      if (cur) tokens.push(cur), (cur = "");
      continue;
    }
    cur += ch;
  }
  if (cur) tokens.push(cur);
  return tokens;
}

function convertCurlToFetch(cmd) {
  const t = tokenizeCurl(cmd);
  if (!t.length) throw new Error("Paste a curl command first.");
  if (t[0] !== "curl") throw new Error("Input should start with: curl ...");

  let url = "";
  let method = "";
  const headers = {};
  let body = null;

  for (let i = 1; i < t.length; i++) {
    const tok = t[i];
    const next = () => (i + 1 < t.length ? t[i + 1] : "");

    if (tok === "-X" || tok === "--request") {
      method = next();
      i++;
      continue;
    }
    if (tok === "-H" || tok === "--header") {
      const h = next();
      i++;
      const idx = h.indexOf(":");
      if (idx > 0) {
        const k = h.slice(0, idx).trim();
        const v = h.slice(idx + 1).trim();
        if (k) headers[k] = v;
      }
      continue;
    }
    if (tok === "-d" || tok === "--data" || tok === "--data-raw" || tok === "--data-binary") {
      body = next();
      i++;
      if (!method) method = "POST";
      continue;
    }
    if (!tok.startsWith("-") && !url) {
      url = tok;
      continue;
    }
  }

  if (!url) throw new Error("Could not find URL in curl command.");
  if (!method) method = body != null ? "POST" : "GET";

  const opts = {};
  opts.method = method.toUpperCase();
  if (Object.keys(headers).length) opts.headers = headers;
  if (body != null) opts.body = body;

  const js = `// Generated by Toolbox\n` +
    `const url = ${JSON.stringify(url)};\n` +
    `const options = ${JSON.stringify(opts, null, 2)};\n\n` +
    `const res = await fetch(url, options);\n` +
    `const text = await res.text();\n` +
    `console.log(res.status, text);\n`;
  return js;
}

function run() {
  try {
    show("");
    const raw = input.value ?? "";
    if (!raw.trim()) {
      setText(out, "");
      return show("Paste a curl command first.", true);
    }
    if (raw.length > MAX_INPUT_CHARS) {
      setText(out, "");
      return show(`Input too large (max ${MAX_INPUT_CHARS.toLocaleString()} chars).`, true);
    }
    const js = convertCurlToFetch(raw);
    if (js.length > MAX_OUTPUT_CHARS) {
      setText(out, "");
      return show("Output too large to display.", true);
    }
    setText(out, js);
    show("Converted.");
    window.ToolboxTracking?.trackRun("curl-to-fetch", "convert");
  } catch (e) {
    setText(out, "");
    show(e instanceof Error ? e.message : "Failed to convert curl.", true);
  }
}

runBtn.addEventListener("click", run);
copyBtn.addEventListener("click", async () => {
  try {
    const text = out.textContent || "";
    if (!text) return show("Nothing to copy.", true);
    if (text.length > MAX_OUTPUT_CHARS) return show("Output too large to copy safely.", true);
    await copyText(text);
    show("Copied!");
    flashCopied(out);
    window.setTimeout(() => {
      if ((status.textContent || "").trim() === "Copied!") show("");
    }, 1200);
  } catch (e) {
    show(e instanceof Error ? e.message : "Failed to copy output.", true);
  }
});
clearBtn.addEventListener("click", () => {
  try {
    input.value = "";
    setText(out, "");
    show("");
  } catch (e) {
    show(e instanceof Error ? e.message : "Failed to clear.", true);
  }
});

